### ISSUE TITLE
Open.HttpProxy csproj Can we split a library of dotnet core

### ISSUE THREAD

**Issue by fjqingyou** [lontivero/Open.HttpProxy#2]
For secondary development

The expectation is not to modify any code in the library. Can I refer to this library through inheritance or interface implementation?

Do not modify the code. It's for git pull update and git push add possible common function or fix bug

**Comment by fjqingyou** [comment]
Hope git submodule add gitAddress using it

**Comment by lontivero** [comment]
Nobody is maintaining the project and it is still a work in progress. Do not use it.
